name: Deploy static content to Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pages: write
      actions: read
      id-token: write
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and Render
        shell: bash
        run: |
          function retry {
            local n=1
            local max=5
            local delay=1
            while true; do
              "$@" && break || {
                if [[ $n -lt $max ]]; then
                  ((n++))
                  echo "Command failed. Attempt $n/$max:"
                  sleep $delay;
                else
                  echo "The command has failed after $n attempts."
                  return 1
                fi
              }
            done
          }
          retry npm run predeploy
        env:
          NODE_ENV: production

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Correct version (v3)
        with:
          path: ./build # Ensure this points to the correct build directory

      - name: Sleep before deploy
        run: |
          echo "Sleeping for 10 seconds to wait for artifact to be available..."
          sleep 10  # Wait 10 seconds before proceeding

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3 # Ensure using v3 of the deploy action
        with:
          artifact_name: github-pages # Ensure this matches the artifact name uploaded
