name: Deploy static content to Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and Render
        shell: bash
        run: |
          function retry {
            local n=1
            local max=5
            local delay=1
            while true; do
              "$@" && break || {
                if [[ $n -lt $max ]]; then
                  ((n++))
                  echo "Command failed. Attempt $n/$max:"
                  sleep $delay;
                else
                  echo "The command has failed after $n attempts."
                  return 1
                fi
              }
            done
          }
          retry npm run predeploy
        env:
          NODE_ENV: production

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./build # Ensure this matches the build output directory

  deploy:
    runs-on: ubuntu-20.04
    needs: build # Ensures the deploy job runs only after the build job succeeds
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Display Run ID
        run: echo "The workflow run ID is ${{ github.run_id }}"

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build # Ensure this points to the correct build directory

      - name: Sleep before deployment
        run: |
          echo "Sleeping for 10 seconds to wait for artifact to be available..."
          sleep 10

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
